OPENAI_API_KEY: YOUR_OPEN_API_KEY

WEAVIATE_URL: YOUR_WEAVIATE_URL
WEAVIATE_API_KEY: YOUR_WEAVIATE_API_KEY

# GITHUB
GITHUB_USERNAME: YOUR_GITHUB_USERNAME
GITHUB_ACCESS_TOKEN: YOUR_GITHUB_ACCESS_TOKEN